### ISSUE TITLE
Pressing the red X in the upper right corner to exit the computer may cause to fall to death

### ISSUE THREAD

**Issue by mocksonline** [PolymerPorts/cc-tweaked-patch#1]
![70f5b7edcf2c6a8e42eef6118e77768a](https://github.com/PolymerPorts/cc-tweaked-patch/assets/99143323/43ced89b-5414-48b4-aacb-fbbf1e4027e3)
![e101a31029956177e4ff9f501a1e6d09](https://github.com/PolymerPorts/cc-tweaked-patch/assets/99143323/3cacfc25-cc7f-4090-8749-878dddb438a4)

**Comment by mocksonline** [comment]
1.109.6.0+1.20.4

Additional explanation, using ctrl+q also kill

**Comment by unilock** [comment]
This can also happen with [Anshar](https://github.com/Anshar-Eternalis/anshar) (with the [Polymer patch](https://github.com/PolymerPorts/anshar-patch)) when descending from the "transposition" menu, as well as when opening a CC Turtle's inventory.

Maybe it's due to an incompatibility with some other mod? @mocksonline, what other mods do you have installed on the server?
